version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    container_name: htron-theme-mysql
    environment:
      MYSQL_ROOT_PASSWORD: htronWpTheme
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
    - ~/docker/volumes/mysql:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: htron-theme-wordpress
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/wp-content/themes/htron-theme
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: hwp
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA:  |
        define('FS_METHOD','direct');